### ISSUE TITLE
Memory leak spring boot, Jersey 2 and tomcat 8 embedded.

### ISSUE THREAD

**Issue by farchanjo** [fge/json-schema-validator#155]
Hi,

I'm using spring boot with Jersey 2.  I create a spring component for validate to all json. Take a look:
```java
@Component
public class JSONValidator {
    private final Logger logger = LoggerFactory.getLogger(JSONValidator.class);
    private final JsonValidator jsonValidator = JsonSchemaFactory.byDefault().getValidator();
    private Map<String, JsonNode> schemas = new ConcurrentHashMap<>(1024);
    private JsonNode jsonForValidade;

    public synchronized ProcessingReport validate(String schemaName, Serializable jsonToValidade) {
        this.convertJsonToObject(jsonToValidade);
        return jsonValidator.validateUnchecked(this.getSchema(schemaName), jsonForValidade);
    }

    private JsonNode getSchema(String schemaName) {
        if (schemas.get(schemaName) != null) {
            return schemas.get(schemaName);
        } else {
            try {
                schemas.put(schemaName, JsonLoader.fromResource("/jsons/" + schemaName + ".json"));
            } catch (IOException e) {
                logger.error(e.getMessage());
            }
            return schemas.get(schemaName);
        }
    }

    private void convertJsonToObject(Serializable jsonToConvert) {
        this.jsonForValidade = new ObjectMapper().setSerializationInclusion(JsonInclude.Include.NON_NULL).valueToTree(jsonToConvert);
    }
}
```

![screenshot 2015-03-29 18 25 38](https://cloud.githubusercontent.com/assets/4031556/6890628/5c8697a2-d685-11e4-8463-5160653384f3.png)

As we can see, there are lot of ListProcessingReport. Is there a better way or another way to validate without create a memory leak? 

Thank you,

Fabricio

**Comment by fge** [comment]
OK, first, what is a component? Sorry, I don't do Spring at all, so I have no idea how it works etc. In particular, how often is it initialized?

Also, note that there is the `resource` scheme; you can use that instead of `JsonLoader.fromResource()`.

**Comment by ddossot** [comment]
@farchanjo Is it possible that the caller of `JSONValidator.validate()` holds a reference to `ProcessingReport`, thus creating the leak?

Also, I think there's a design issue in `JSONValidator`: it should better be made stateless be removing the `jsonForValidade` and returning the `JSONNode` straight from `convertJsonToObject`. This would remove a class of problems, also allowing you to remove the `synchronized` block.

Also `ObjectMapper` is thread safe so you can instantiate it only once and store in a constant.

**Comment by farchanjo** [comment]
Hi @ddossot and @fge. 

@fge , Spring is a dependency inject. When the context is running all @Component class is instantiated as singleton inside of spring. I use this component on my resource class validating all json.  

@ddossot , sorry, I'm using syncronized to avoid race conditions on my api resource. I didnt know about the object mapper is thread-safe, sorry, I just put it for design.

Take a look my resource api:

```java
@POST

    public Response emailSend(EmailDTO emailDTO) {
        try {
            ProcessingReport report = this.jsonValidator.validate("email-send", emailDTO);
            if (report.isSuccess()) {
                return Response.ok(email.enqueue(emailDTO)).build();
            } else {
                return Response.status(Response.Status.BAD_REQUEST).entity(((AsJson) report).asJson()).build();
            }
        } catch (Exception e) {
            logger.error(e.getMessage());
        }
        return Response.status(Response.Status.INTERNAL_SERVER_ERROR).entity(this.erroApi()).build();
    }
```
I'm using JsonNode as class attribute to create just single object to handle all calls from api resource. I think there is not issue related to JsonNode, just in ListProcessingReport.

**Comment by ddossot** [comment]
It's true that the reference to `report` is not kept in `emailSend` so, even with the useless state in `jsonForValidade` issue, I don't think the culprit is there. This said, it's worth doing this simple refactoring as using stateless components is a best practice with Spring.

What's interesting is that the elevated number of `ListProcessingReport` matches the size of the Google cache, which I think is used internally by the JSON Schema Validator loader.

This makes me wonder if:

1. The ad hoc schema cache in `JSONValidator` is useful at all, since it seems `JsonLoader` also has an internal cache,
2. A reference is accidently maintained between this schema cache and the processing reports.

Also @farchanjo are you sure your Spring component is a singleton and not a prototype?

**Comment by farchanjo** [comment]
@ddossot sure!! 
I'm using Prototype componet just for processing email in thread pool, but it internaly on my service. Did u see a lot of Arraylist? It's matching to ListProcessing too. My service without schema library keep ~150MB, if I enable this library my heap can reach 2G after 60000 requests..

**Comment by ddossot** [comment]
`ListProcessingReport` encapsulates an `ArrayList` instance (see: https://github.com/fge/json-schema-core/blob/master/src/main/java/com/github/fge/jsonschema/core/report/ListProcessingReport.java#L42 ) so it's expected to see a matching number.

The question is what does keep a reference to `ListProcessingReport`? Can you use a memory analyzer tool to find out the reference?

**Comment by fge** [comment]
One thing you should try is not to use your current schema loading strategy, but use `JsonSchemaFactory`'s loading methods instead.

What happens here is that since the factory is not aware of the URIs of your schemas, it will load it as new each and every time. Use `.load("resource:/jsons/" + schemaName)` from the factory. There is no reason why you should maintain a map when the validator has in fact this builtin ;)

The number of `ProcessingReport`s generated is because the factory will cache the results of all syntax validations. And given the way you use it right now, it caches one each time you load a schema.

SHould you use the factory to load instead, only one report will be cached per URI.

**Comment by farchanjo** [comment]
@fge  how it will be load too many time if I use the validator as singleton? 

Sorry, I didn't understand it very well..

I looked at JsonSchemaFactory and I have not found the .load method.

**Comment by fge** [comment]
The method is called `.getJsonSchema()`; you pass it a string as an argument which is the URI of the schema:

```java
factory.getJsonSchema("resource:/schemas/myschema.json")
```

Note that it has full JSON Reference support which means you can use a JSON Pointer to address only a certain part of the schema etc.

**Comment by farchanjo** [comment]
@fge,
Thanks. I'm gonna try later and bring feedback here.

**Comment by farchanjo** [comment]
@fge @ddossot 
Thank you for support!! It's working now! 

![screenshot 2015-03-31 17 46 13](https://cloud.githubusercontent.com/assets/4031556/6929021/16cb9c22-d7ce-11e4-87ed-d15986e36dae.png)

I have made 100k request on api and heap keep around 150MB.

**Comment by ddossot** [comment]
:dancers: Excellent news!
