### ISSUE TITLE
Getting 403 return code when initializing SchemaVersion class

### ISSUE THREAD

**Issue by odieduck** [fge/json-schema-validator#167]
Stacktrace:
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: http://json-schema.org/draft-04/schema#
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1839)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
	at com.github.fge.jsonschema.SchemaVersion.<init>(SchemaVersion.java:73)

**Comment by box-jhuffaker** [comment]
I'm not entirely familiar with this part of the codebase, but if you are running in a production environment with tight firewall rules at layer7 then it's possible that it is denying an outbound request?  

Maybe try running curl from the server as a connectivity check?  Here it is from my laptop:
jhuffaker@mbp-003138 ~ $ curl -v http://json-schema.org/draft-04/schema#
*   Trying 192.30.252.154...
* Connected to json-schema.org (192.30.252.154) port 80 (#0)
> GET /draft-04/schema HTTP/1.1
> Host: json-schema.org
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: GitHub.com
< Date: Tue, 13 Oct 2015 17:28:33 GMT
< Content-Type: application/octet-stream
< Content-Length: 4375
< Last-Modified: Fri, 09 Oct 2015 15:36:12 GMT
< Access-Control-Allow-Origin: *
< Expires: Tue, 13 Oct 2015 17:38:33 GMT
< Cache-Control: max-age=600
< Accept-Ranges: bytes


As a side note it seems like we could and maybe should load a resource like this from the jar itself instead of via the network to avoid issues like this.  I think we package the schema in the jar, I haven't explored the API maybe it's an easy switch.

**Comment by box-jhuffaker** [comment]
What version of json-schema-validator are you on?  The line numbers you are showing don't line up with the latest versions.

**Comment by box-jhuffaker** [comment]
My reading of the current code is if it looks like it loads from the JAR.

**Comment by box-jhuffaker** [comment]
Do you have any more info in the stack trace.   I don't see how this is happening in reading the code.

**Comment by odieduck** [comment]
Ahh.. The problem is not with json-schema-validator. It is with json-schema-core. 

Closing this issue and opening the issue in json-schema-core.
